name = "OWEATHER_MODULE"
description = "A weather module using the OpenWeather API"
version = "1.0.3"
github = "Nadybot/OWEATHER_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"
