name = "OWEATHER_MODULE"
description = "A weather module using the OpenWeather API"
version = "1.0.0"
github = "Nadybot/OWEATHER_MODULE"
author = "Nadyita"
bot_type = "Nadybot"
bot_version = "^5.0.0-beta1"
